name: Update metadata files for APM

on:
  workflow_dispatch:
  schedule:
     - cron: "30 1 1,15 * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-update-versions:
    name: Update metadata files for APM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure git
        run: |
          git config user.name pauljwil
          git config user.email paulw@splunk.com

      - run: ./scripts/update-all.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
